### ISSUE TITLE
Identify core packages

### ISSUE THREAD

**Issue by szipper** [ropensci/hydrometeorology#13]
From Achim: 

> You currently haven't selected any "core" packages, i.e., those package
> that you most people would need to do hydrology in R. (As currently there
> is none, the .ctv as an empty: `<pkg priority="core"></pkg>`.)

**Comment by szipper** [comment]
I added a few in commit 49f4b48 ... Feel free to add more if there's packages you use a lot!

**Comment by ilapros** [comment]
Added nsRFA as core and modified the buildxml.R file so it detects core packages in commit d1ac5a51d7f0b1129d39469abe71d5adbc1eae40

**Comment by boshek** [comment]
Two points. The markdown based workflow we are using has I think a better method of specifying core package using this [line](https://github.com/ropensci/hydrometeorology/blame/49f4b4824ca1249a959847f156bb27fa91ecf2eb/buildxml.R#L7) (much like [here](https://github.com/ropensci/webservices/blob/master/buildxml.R#L7)). I think this is a cleaner place to identify core packages. I will make that change if folks are ok with that. 

Second - what is our theme for core packages? Is it data packages? Is it modelling? Is it our favourite packages? By this definition:

> those package that you most people would need to do hydrology in R

I wonder if data packages might be the best thing? Or modelling?

**Comment by ilapros** [comment]
I had modified the R file so we only need to modify the .md file (since there had been some additions as "core" packages which had not been reflected in the .ctv file), but I can see that this is something which can be done in the .R file since the list of core packages won't change rapidly.  Happy either way -  let's decide on which approach to take and we can implement accordingly. 

I think core packages would be stable and reliable packages without which one can not even consider doing anything, and it is very difficult for me to pin a few of these down for the water sciences. I would give the "core" badge to packages which are well maintained and have a large user-base, for example nsRFA is used a lot in flood frequency analysis and is maintained. dataRetrieval is another one that does a lot and is widely used - but I am not a water scientist, so it is hard for me to judge.

**Comment by szipper** [comment]
Yeah, I agree it's hard to define a 'core' package because Water Science is such a good idea. I agree with @ilapros criteria of stable + large user base, so I just chose ones that I use a lot and I think other people also use... That seems like a decent enough definition for now.

**Comment by boshek** [comment]
Sounds good to me. Certainly I can be fluid as well. Because of regional variations in demands I wonder if we should exclude any data packages from "core". I can't think of a good reason why if we include one data package we shouldn't include them all.

**Comment by szipper** [comment]
Agreed!
