### ISSUE TITLE
Info collapse

### ISSUE THREAD

**Issue by szipper** [ropensci/hydrometeorology#14]
From Achim:

> Collapsing all the `<info>` into a single might not be ideal for
> maintenance of the .ctv file. Note that I will regularly edit the .ctv
> when packages on CRAN get archived (and less often also wehn packages get
> un-archived). I've pointed out the same problem to the WebTechnologies
> maintainers.

I don't think I understand what he means here, probably because I don't really understand the CTV file generation process. @boshek , does this make sense to you?

**Comment by boshek** [comment]
I think it is fine. Here he is assuming (I think) we are interacting directly with the ctv and [this](https://github.com/ropensci/hydrometeorology/blob/87b4db245cc831a764cc7b876f2b80e5b9372a1c/hydrometeorology.ctv#L6-L8) super long line would be very cumbersome to deal with. However since we are dealing directly with the .md file I think we can safely ignore this concern.
